#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <SDL3_image/SDL_image.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <SDL3_mixer/SDL_mixer.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>
#include <sys/wait.h>

static MIX_Mixer *mixer=NULL; static MIX_Audio *music=NULL; static MIX_Track *music_track=NULL;
static SDL_Window *window=NULL; static SDL_Renderer *renderer=NULL; static SDL_Texture *logo_texture=NULL,*background_texture=NULL,*cover_texture=NULL; static TTF_Font *font=NULL;
#define INPUT_COOLDOWN_MS 200
#define AXIS_DEADZONE 8000
#define LOGO_HEIGHT 200
#define FONT_SIZE 18
#define MAX_INPUT_LENGTH 256
static Uint64 last_input_time=0; static char input_text[MAX_INPUT_LENGTH]=""; static int typing_in_input=0;
typedef struct{const char*dir_name,*display_name,*mame_sys,*launch_arg,*allowed_exts;}SystemEntry;
static const SystemEntry systems[]={
{"sms1","Master System","sms1","-cart","sms,bin,zip"},{"genesis","Mega Drive","genesis","-cart","md,bin,zip"},{"snes","Super Nintendo","snes","-cart","smc,sfc,zip"},{"nes","Nintendo 8-bit","nes","-cart","nes,zip"},{"segacd","Mega CD","segacd","-cdrom","cue,chd,iso"},{"psu","PlayStation 1","psu","-cdrom","cue,chd,iso"},{"ps2","PlayStation 2","pcsx2",NULL,"iso,chd,cso"},{"neogeo","Neo Geo","neogeo",NULL,"neo"}};
static int selected_system_index=0,system_scroll_offset=0,in_rom_menu=0; static int system_menu_count=sizeof(systems)/sizeof(SystemEntry)+2;
typedef struct{char*display_name,*rom_path;}RomEntry; static RomEntry *all_rom_list=NULL,*rom_list=NULL; static int all_rom_count=0,rom_count=0,selected_rom_index=0,rom_scroll_offset=0;
static void free_rom_list(void);static void free_all_rom_list(void);static void filter_rom_list(void);static int has_allowed_extension(const char*,const char*);static void render_text(const char*,float,float,SDL_Color);static void render_text_centered(const char*,float,SDL_Color);static int file_exists(const char*);static SDL_Texture*load_cover_for_rom(const char*);
static void draw_scrollbar(int n,int v,int o,int y,int lh,int w){if(n<=v||v<=0)return;float sh=v*lh,hh=sh*(v/(float)n);if(hh<10)hh=10;float hy=y+(o/(float)(n-v))*(sh-hh);SDL_FRect b={w-20.0f,(float)y,8,sh},h={w-20.0f,hy,8,hh};SDL_SetRenderDrawColor(renderer,80,80,80,200);SDL_RenderFillRect(renderer,&b);SDL_SetRenderDrawColor(renderer,200,200,200,255);SDL_RenderFillRect(renderer,&h);}
static void draw_system_menu(void){int w,h;SDL_GetWindowSize(window,&w,&h);int lh=FONT_SIZE+10,v=(h-LOGO_HEIGHT-40)/lh;if(selected_system_index<system_scroll_offset)system_scroll_offset=selected_system_index;if(selected_system_index>=system_scroll_offset+v)system_scroll_offset=selected_system_index-v+1;int y=LOGO_HEIGHT+20;for(int i=system_scroll_offset;i<system_menu_count&&i<system_scroll_offset+v;i++){SDL_Color c={200,200,200,255};if(i==selected_system_index)c.r=c.g=255;const char*l=i<system_menu_count-2?systems[i].display_name:(i==system_menu_count-2?"Run Cover Scraper":"Exit");render_text_centered(l,y+(i-system_scroll_offset)*lh,c);}draw_scrollbar(system_menu_count,v,system_scroll_offset,y,lh,w);}
static void draw_search_field(void){int w,h;SDL_GetWindowSize(window,&w,&h);float y=h-FONT_SIZE-42;SDL_FRect r={50,y,w-100.0f,FONT_SIZE+10.0f};SDL_SetRenderDrawColor(renderer,50,50,50,210);SDL_RenderFillRect(renderer,&r);SDL_SetRenderDrawColor(renderer,typing_in_input?255:110,typing_in_input?255:110,typing_in_input?0:110,255);SDL_RenderRect(renderer,&r);char t[MAX_INPUT_LENGTH+32];snprintf(t,sizeof(t),"Search [TAB]: %s%s",input_text,typing_in_input&&((SDL_GetTicks()/500)%2)?"|":"");render_text(t,56,y+5,(SDL_Color){255,255,255,255});}
static void draw_rom_menu(void){int w,h;SDL_GetWindowSize(window,&w,&h);int lh=FONT_SIZE+10,v=(h-LOGO_HEIGHT-80)/lh;if(selected_rom_index<rom_scroll_offset)rom_scroll_offset=selected_rom_index;if(selected_rom_index>=rom_scroll_offset+v)rom_scroll_offset=selected_rom_index-v+1;int y=LOGO_HEIGHT+20;for(int i=rom_scroll_offset;i<rom_count&&i<rom_scroll_offset+v;i++){SDL_Color c={200,200,200,255};if(i==selected_rom_index)c.r=c.g=255;render_text_centered(rom_list[i].display_name,y+(i-rom_scroll_offset)*lh,c);}draw_scrollbar(rom_count,v,rom_scroll_offset,y,lh,w);if(rom_list&&rom_count>0&&selected_rom_index<rom_count&&rom_list[selected_rom_index].rom_path){if(cover_texture)SDL_DestroyTexture(cover_texture);cover_texture=load_cover_for_rom(rom_list[selected_rom_index].rom_path);if(!cover_texture)cover_texture=IMG_LoadTexture(renderer,"assets/cover.png");if(cover_texture){SDL_FRect d={w-230.0f,30,220,220};SDL_RenderTexture(renderer,cover_texture,NULL,&d);}}draw_search_field();}
static void render_text_centered(const char*t,float y,SDL_Color c){SDL_Surface*s=TTF_RenderText_Blended(font,t,SDL_strlen(t),c);if(!s)return;SDL_Texture*x=SDL_CreateTextureFromSurface(renderer,s);int tw=s->w,th=s->h;SDL_DestroySurface(s);if(!x)return;int w;SDL_GetWindowSize(window,&w,NULL);SDL_FRect d={(w-tw)/2.0f,y,(float)tw,(float)th};SDL_RenderTexture(renderer,x,NULL,&d);SDL_DestroyTexture(x);}static void render_text(const char*t,float x,float y,SDL_Color c){SDL_Surface*s=TTF_RenderText_Blended(font,t,SDL_strlen(t),c);if(!s)return;SDL_Texture*z=SDL_CreateTextureFromSurface(renderer,s);int w=s->w,h=s->h;SDL_DestroySurface(s);if(!z)return;SDL_FRect d={x,y,(float)w,(float)h};SDL_RenderTexture(renderer,z,NULL,&d);SDL_DestroyTexture(z);}
static int has_allowed_extension(const char*f,const char*a){const char*d=strrchr(f,'.');if(!d||d==f)return 0;char e[16],tmp[64];SDL_strlcpy(e,d+1,sizeof(e));SDL_strlcpy(tmp,a,sizeof(tmp));for(char*t=strtok(tmp,",");t;t=strtok(NULL,","))if(!SDL_strcasecmp(e,t))return 1;return 0;}
static void load_rom_list(const SystemEntry*s){free_rom_list();free_all_rom_list();char p[512];snprintf(p,sizeof(p),"./roms/%s/",s->dir_name);DIR*d=opendir(p);if(!d)return;int cap=20;all_rom_list=calloc(cap,sizeof(RomEntry));struct dirent*e;while((e=readdir(d))){if(!strcmp(e->d_name,".")||!strcmp(e->d_name,".."))continue;char fp[1024];snprintf(fp,sizeof(fp),"%s%s",p,e->d_name);struct stat st;if(stat(fp,&st))continue;if(S_ISREG(st.st_mode)&&has_allowed_extension(e->d_name,s->allowed_exts)){if(all_rom_count>=cap){cap*=2;all_rom_list=realloc(all_rom_list,cap*sizeof(RomEntry));}all_rom_list[all_rom_count].display_name=strdup(e->d_name);all_rom_list[all_rom_count++].rom_path=strdup(fp);}}rewinddir(d);while((e=readdir(d))){if(!strcmp(e->d_name,".")||!strcmp(e->d_name,".."))continue;char sp[1024];snprintf(sp,sizeof(sp),"%s%s",p,e->d_name);struct stat st;if(stat(sp,&st)||!S_ISDIR(st.st_mode))continue;DIR*sd=opendir(sp);if(!sd)continue;struct dirent*se;while((se=readdir(sd)))if(se->d_type==DT_REG&&has_allowed_extension(se->d_name,s->allowed_exts)){if(all_rom_count>=cap){cap*=2;all_rom_list=realloc(all_rom_list,cap*sizeof(RomEntry));}char fp[1024];snprintf(fp,sizeof(fp),"%s/%s",sp,se->d_name);all_rom_list[all_rom_count].display_name=strdup(se->d_name);all_rom_list[all_rom_count++].rom_path=strdup(fp);}closedir(sd);}closedir(d);filter_rom_list();}
static void free_all_rom_list(void){if(all_rom_list){for(int i=0;i<all_rom_count;i++){SDL_free(all_rom_list[i].display_name);SDL_free(all_rom_list[i].rom_path);}SDL_free(all_rom_list);}all_rom_list=NULL;all_rom_count=0;}static void free_rom_list(void){SDL_free(rom_list);rom_list=NULL;rom_count=0;if(cover_texture){SDL_DestroyTexture(cover_texture);cover_texture=NULL;}}static void filter_rom_list(void){free_rom_list();rom_list=calloc(all_rom_count+1,sizeof(RomEntry));if(!rom_list)return;for(int i=0;i<all_rom_count;i++)if(!input_text[0]||SDL_strcasestr(all_rom_list[i].display_name,input_text))rom_list[rom_count++]=all_rom_list[i];rom_list[rom_count].display_name="Exit";rom_list[rom_count++].rom_path=NULL;selected_rom_index=rom_scroll_offset=0;}static void leave_rom_menu(void){typing_in_input=0;SDL_StopTextInput(window);input_text[0]=0;in_rom_menu=0;free_rom_list();free_all_rom_list();}static void move_selection(int d){if(typing_in_input)return;if(in_rom_menu){if(rom_count)selected_rom_index=(selected_rom_index+rom_count+d)%rom_count;}else selected_system_index=(selected_system_index+system_menu_count+d)%system_menu_count;}
static void activate_selection(void){if(typing_in_input)return;if(in_rom_menu){if(!rom_list||!rom_count)return;if(!rom_list[selected_rom_index].rom_path){leave_rom_menu();return;}const SystemEntry*s=&systems[selected_system_index];const char*rp=rom_list[selected_rom_index].rom_path;if(music_track)MIX_PauseTrack(music_track);char cmd[4096];if(!strcmp(s->mame_sys,"neogeo")){const char*n=strrchr(rp,'/');n=n?n+1:rp;const char*d=strrchr(n,'.');char id[256];size_t z=d?(size_t)(d-n):strlen(n);if(z>=sizeof(id))z=sizeof(id)-1;memcpy(id,n,z);id[z]=0;snprintf(cmd,sizeof(cmd),"mame neogeo '%s'",id);}else if(!strcmp(s->mame_sys,"pcsx2")){snprintf(cmd,sizeof(cmd),"if command -v pcsx2-qt >/dev/null 2>&1; then pcsx2-qt -batch -fullscreen '%s'; elif command -v pcsx2 >/dev/null 2>&1; then pcsx2 -batch -fullscreen '%s'; else echo 'PCSX2 not found'; fi",rp,rp);}else snprintf(cmd,sizeof(cmd),"mame %s %s '%s'",s->mame_sys,s->launch_arg,rp);system(cmd);if(music_track)MIX_ResumeTrack(music_track);leave_rom_menu();return;}if(selected_system_index==system_menu_count-1)exit(0);if(selected_system_index==system_menu_count-2){pid_t p=fork();if(!p){execl("./cover-scraper","./cover-scraper",(char*)NULL);_exit(1);}if(p>0){int s;waitpid(p,&s,0);}return;}input_text[0]=0;load_rom_list(&systems[selected_system_index]);in_rom_menu=1;}
static void handle_events(const SDL_Event*e){if(e->type==SDL_EVENT_TEXT_INPUT&&typing_in_input){size_t l=MAX_INPUT_LENGTH-1-strlen(input_text);if(l){strncat(input_text,e->text.text,l);filter_rom_list();}return;}if(e->type!=SDL_EVENT_KEY_DOWN||e->key.repeat)return;if(in_rom_menu&&e->key.key==SDLK_TAB){typing_in_input=!typing_in_input;if(typing_in_input)SDL_StartTextInput(window);else SDL_StopTextInput(window);return;}if(typing_in_input){if(e->key.key==SDLK_BACKSPACE&&input_text[0]){input_text[strlen(input_text)-1]=0;filter_rom_list();}else if(e->key.key==SDLK_RETURN||e->key.key==SDLK_KP_ENTER){typing_in_input=0;SDL_StopTextInput(window);}else if(e->key.key==SDLK_ESCAPE){typing_in_input=0;SDL_StopTextInput(window);input_text[0]=0;filter_rom_list();}return;}switch(e->key.key){case SDLK_UP:move_selection(-1);break;case SDLK_DOWN:move_selection(1);break;case SDLK_RETURN:case SDLK_KP_ENTER:case SDLK_SPACE:activate_selection();break;case SDLK_ESCAPE:if(in_rom_menu)leave_rom_menu();break;default:break;}}
static void handle_joystick_input(const SDL_Event*e){if(typing_in_input)return;Uint64 n=SDL_GetTicks();if(n<last_input_time+INPUT_COOLDOWN_MS)return;if(e->type==SDL_EVENT_JOYSTICK_AXIS_MOTION&&e->jaxis.axis==1){int d=e->jaxis.value<-AXIS_DEADZONE?-1:e->jaxis.value>AXIS_DEADZONE?1:0;if(d){move_selection(d);last_input_time=n;}}if(e->type==SDL_EVENT_JOYSTICK_BUTTON_DOWN&&!e->jbutton.button){activate_selection();last_input_time=n;}}
static int file_exists(const char*p){struct stat s;return !stat(p,&s);}static SDL_Texture*load_cover_for_rom(const char*rp){if(!rp)return NULL;const char*f=strrchr(rp,'/');f=f?f+1:rp;const char*d=strrchr(f,'.');int n=d?(int)(d-f):(int)strlen(f);char p[512];snprintf(p,sizeof(p),"./covers/%.*s.png",n,f);if(file_exists(p)){SDL_Texture*t=IMG_LoadTexture(renderer,p);if(t)return t;}snprintf(p,sizeof(p),"./covers/%.*s.jpg",n,f);return file_exists(p)?IMG_LoadTexture(renderer,p):NULL;}
int main(int argc,char**argv){SDL_Init(SDL_INIT_VIDEO|SDL_INIT_JOYSTICK|SDL_INIT_AUDIO);TTF_Init();SDL_CreateWindowAndRenderer("Joystick Menu",1024,768,0,&window,&renderer);font=TTF_OpenFont("assets/Roboto-Regular.ttf",FONT_SIZE);logo_texture=IMG_LoadTexture(renderer,"assets/logo.png");background_texture=IMG_LoadTexture(renderer,"assets/background.jpg");if(background_texture){SDL_SetTextureBlendMode(background_texture,SDL_BLENDMODE_BLEND);SDL_SetTextureAlphaMod(background_texture,80);}if(MIX_Init()){mixer=MIX_CreateMixerDevice(SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK,NULL);if(mixer){music=MIX_LoadAudio(mixer,"assets/background1.ogg",false);if(music){music_track=MIX_CreateTrack(mixer);if(music_track&&MIX_SetTrackAudio(music_track,music)){MIX_SetTrackGain(music_track,.5f);SDL_PropertiesID p=SDL_CreateProperties();SDL_SetNumberProperty(p,MIX_PROP_PLAY_LOOPS_NUMBER,-1);MIX_PlayTrack(music_track,p);SDL_DestroyProperties(p);}}}}SDL_Event e;int run=1;while(run){while(SDL_PollEvent(&e)){if(e.type==SDL_EVENT_QUIT)run=0;if(e.type==SDL_EVENT_JOYSTICK_ADDED)SDL_OpenJoystick(e.jdevice.which);if(e.type==SDL_EVENT_JOYSTICK_REMOVED)SDL_CloseJoystick(SDL_GetJoystickFromID(e.jdevice.which));handle_events(&e);handle_joystick_input(&e);}int w,h;SDL_GetWindowSize(window,&w,&h);SDL_SetRenderDrawColor(renderer,0,0,0,255);SDL_RenderClear(renderer);if(background_texture){SDL_FRect d={0,0,(float)w,(float)h};SDL_RenderTexture(renderer,background_texture,NULL,&d);}if(logo_texture){SDL_FRect d={(w-200)/2.0f,40,200,100};SDL_RenderTexture(renderer,logo_texture,NULL,&d);}if(in_rom_menu)draw_rom_menu();else draw_system_menu();render_text("by MARCO AURELIO SIMAO",10,h-FONT_SIZE-10,(SDL_Color){150,150,150,255});SDL_RenderPresent(renderer);SDL_Delay(16);}free_rom_list();free_all_rom_list();if(font)TTF_CloseFont(font);if(logo_texture)SDL_DestroyTexture(logo_texture);if(background_texture)SDL_DestroyTexture(background_texture);if(cover_texture)SDL_DestroyTexture(cover_texture);if(music_track)MIX_DestroyTrack(music_track);if(music)MIX_DestroyAudio(music);if(mixer)MIX_DestroyMixer(mixer);MIX_Quit();TTF_Quit();SDL_Quit();return 0;}
